-- Multas
CREATE TRIGGER trg_apply_fine
AFTER INSERT ON SCHEMA_NAME.fine
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.apply_fine_to_wallet();

CREATE TRIGGER trg_apply_fine_payment
AFTER INSERT ON SCHEMA_NAME.fine_payment
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.apply_fine_payment();

-- Auditoria
CREATE TRIGGER audit_app_user
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.app_user
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

CREATE TRIGGER audit_citizen
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.citizen
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

CREATE TRIGGER audit_vehicle
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.vehicle
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

CREATE TRIGGER audit_sensor
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.sensor
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

CREATE TRIGGER audit_fine
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.fine
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

CREATE TRIGGER audit_fine_payment
AFTER INSERT OR UPDATE OR DELETE ON SCHEMA_NAME.fine_payment
FOR EACH ROW EXECUTE FUNCTION SCHEMA_NAME.audit_log_generic();

-- App User
CREATE TRIGGER trg_soft_delete_app_user
BEFORE DELETE ON SCHEMA_NAME.app_user
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.soft_delete_generic();

CREATE TRIGGER trg_block_update_deleted_app_user
BEFORE UPDATE ON SCHEMA_NAME.app_user
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.block_update_deleted_generic();

-- Citizen
CREATE TRIGGER trg_soft_delete_citizen
BEFORE DELETE ON SCHEMA_NAME.citizen
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.soft_delete_citizen_with_user();

CREATE TRIGGER trg_block_update_deleted_citizen
BEFORE UPDATE ON SCHEMA_NAME.citizen
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.block_update_deleted_generic();

-- Vehicle
CREATE TRIGGER trg_soft_delete_vehicle
BEFORE DELETE ON SCHEMA_NAME.vehicle
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.soft_delete_vehicle_with_user();

CREATE TRIGGER trg_block_update_deleted_vehicle
BEFORE UPDATE ON SCHEMA_NAME.vehicle
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.block_update_deleted_generic();

-- Sensor
CREATE TRIGGER trg_soft_delete_sensor
BEFORE DELETE ON SCHEMA_NAME.sensor
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.soft_delete_sensor_with_user();

CREATE TRIGGER trg_block_update_deleted_sensor
BEFORE UPDATE ON SCHEMA_NAME.sensor
FOR EACH ROW
EXECUTE FUNCTION SCHEMA_NAME.block_update_deleted_generic();
