CREATE TRIGGER audit_app_user
AFTER INSERT OR UPDATE OR DELETE ON app_user
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_citizen
AFTER INSERT OR UPDATE OR DELETE ON citizen
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_vehicle
AFTER INSERT OR UPDATE OR DELETE ON vehicle
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_sensor
AFTER INSERT OR UPDATE OR DELETE ON sensor
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_traffic_incident
AFTER INSERT OR UPDATE OR DELETE ON traffic_incident
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_fine
AFTER INSERT OR UPDATE OR DELETE ON fine
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_fine_payment
AFTER INSERT OR UPDATE OR DELETE ON fine_payment
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();

CREATE TRIGGER audit_app_user_notification
AFTER INSERT OR UPDATE OR DELETE ON app_user_notification
FOR EACH ROW
EXECUTE FUNCTION audit_log_generic();
