CREATE OR REPLACE VIEW SCHEMA_NAME.citizen_active AS
SELECT *
FROM SCHEMA_NAME.citizen
WHERE deleted_at IS NULL;

CREATE OR REPLACE VIEW SCHEMA_NAME.vehicle_active AS
SELECT *
FROM SCHEMA_NAME.vehicle
WHERE deleted_at IS NULL;

CREATE OR REPLACE VIEW SCHEMA_NAME.sensor_active AS
SELECT *
FROM SCHEMA_NAME.sensor
WHERE deleted_at IS NULL;

CREATE OR REPLACE VIEW SCHEMA_NAME.app_user_active AS
SELECT *
FROM SCHEMA_NAME.app_user
WHERE deleted_at IS NULL;